SELECT * --1458
FROM 
(
SELECT 
TRIM(ADR0N4) AS PFE_ID,
TRIM(AIACTJ) AS PRODUCT_FAMILY,
TRIM(BXKSB3) AS PROJECT_ID,
TRIM(BXJQCM) AS Project_Name,
--TRIM(B.TLSUB4) AS sub_4,
TRIM(GATLTH) AS ISBN13,
CONCAT(B.TLLANG, B.TLISBN) AS ISBN10,
TRIM(B.TLUXCD) as Originating_Location,
TRIM(B.TLAUTH) AS AUTHOR_NAME,
TRIM(BLW8CR) AS COURSE_CODE,
TRIM(A5X4ED) AS SUBJECT_GROUP,
TRIM(B.TLTITL) AS CORE_TITLE,
TRIM(B.TLFTP1 || B.TLFTP2 || B.TLFTP3) AS FULL_TITLE,	
TRIM(B.TLPROD) AS Product_line,
TRIM(A5RPDF) AS Product_Line_desc,
TRIM(BXPROD) AS Proj_level_Product_line,
TRIM(COALESCE(B3VDED, '')) AS SPT,
TRIM(B.TLSTAT) AS Status, 
TRIM(B.TLXDCD) AS PPC,
TRIM(B.TLFFCD) AS Sponsor_code,
TRIM(B.TLW0CD) AS edition,
TRIM(A5SJDF) AS SC_BU,
TRIM(A6T0DF) AS SC_BV,
TRIM(A6AXEE) AS SC_LOB,
TRIM(A6AYEE) AS SC_LOR,
TRIM(EBSJDF) AS GBPM_BU,
TRIM(EBT0DF) AS GBPM_BV,
TRIM(BWFMEE) AS GBPM_LOB, 
TRIM(BWFNEE) AS GBPM_LOR,
TRIM(B.TLEDIT) AS Editor_Code,
TRIM(A5X5ED) AS Editor_Name,
TRIM(BXP6DD) AS PMC,
distadmin.CVTDATE(B.TLULDT) AS IN_STORE_DATE,
B.TLE6PR AS gbpm_list_price,
us.TLE6PR AS us_list_price,
uk.TLE6PR AS uk_list_price
FROM 
GBPMPDTFL.MFMTITP B
LEFT JOIN GBPMPDTFL.W9A5REP a5 ON a5.A5RMDF = CONCAT(B.TLLANG, B.TLISBN)
LEFT JOIN GBPMPDTFL.W9A6REP a6 ON A6RMDF = CONCAT(B.TLLANG, B.TLISBN)
LEFT JOIN GBPMPDTFL.NMGAREP e ON CONCAT(e.GALANG, e.GAISBN) = CONCAT(B.TLLANG, B.TLISBN)
LEFT JOIN GBPMPDTFL.W7DFCPP df ON CONCAT(df.DFLANG, df.DFISBN) = CONCAT(B.TLLANG, B.TLISBN)
LEFT JOIN GBPMPDTFL.XACYREP sp ON sp.CYQ5DF= df.DFQ5DF
LEFT JOIN GBPMPDTFL.XAB3REP b3 ON b3.B3Q5DF = df.DFQ5DF
LEFT JOIN GOIDTALIB.PVBWCPP bw ON bw.bwi013 = e.GATLTH
LEFT JOIN GBPMPDTFL.NICQCPP cq ON CONCAT(cq.CQLANG, cq.CQISBN) = CONCAT(B.TLLANG, B.TLISBN)
LEFT JOIN GBPMPDTFL.OGAGCPP ON CONCAT(AGLANG,AGISBN) = CONCAT(B.TLLANG, B.TLISBN)
LEFT JOIN GBPMPDTFL.OGAZCPP ON AGR5N4 = AZR5N4
LEFT JOIN GBPMPDTFL.OGADCPP ON AZIBCS = ADIBCS AND AZR0N4 = ADR0N4
LEFT JOIN GBPMPDTFL.N6AIREP ON ADIBCS = AIIBCS
LEFT JOIN GBPMPDTFL.W9EBCPP we ON we.EBRMDF  = CONCAT(B.TLLANG, B.TLISBN)
LEFT JOIN GBPMPDTFL.REBYCPP F ON CONCAT(B.TLLANG, B.TLISBN) = CONCAT(F.BYLANG, F.BYISBN)
LEFT JOIN GBPMPDTFL.W2BWCPP w2 ON we.EBKSB3  = w2.BWKSB3
LEFT JOIN GBPMPDTFL.REBXCPP G ON G.BXKSB3 = F.BYKSB3
LEFT JOIN GBPMPDTFL.XBC1REP xb ON xb.C1SUBJ=B.TLSUBJ
LEFT JOIN E2DISPDTFL.MFMTITP us ON CONCAT(B.TLLANG, B.TLISBN)= CONCAT(us.TLLANG, us.TLISBN)
LEFT JOIN E2UNKPDTFL.MFMTITP uk ON CONCAT(B.TLLANG, B.TLISBN)= CONCAT(uk.TLLANG, uk.TLISBN)
LEFT JOIN GBPMPDTFL.PXBLCPP bl ON CONCAT(B.TLLANG, B.TLISBN)=CONCAT(bl.BLLANG, bl.BLISBN)
--LEFT JOIN E2DISPDTFL.MFMTITP us ON CONCAT(B.TLLANG, B.TLISBN)= CONCAT(us.TLLANG, us.TLISBN)  
WHERE 
TRIM(A6AXEE) IN ('Advanced Content', 'Courseware')  
--AND TRIM(B.TLUXCD) = 'NY'
--AND TRIM(UPPER(B.TLSTAT)) NOT IN ('O', 'K', 'B', 'Z','F', 'R') 
--AND TRIM(UPPER(B.TLXDCD)) NOT IN ('CA', 'DI' ,'SU','D')
--AND COALESCE(B.TLSTAT,'') NOT IN ('')
--AND COALESCE(B.TLUXCD,'') NOT IN ('')
--AND TRIM(B.TLPROD) <> '2'
--AND
--TRIM(GATLTH) in ( '9788126527762') 
GROUP BY
TRIM(ADR0N4),
TRIM(AIACTJ),
TRIM(A5XSED) ,
TRIM(BXKSB3) ,
TRIM(BXJQCM),
TRIM(bw.BWI013) ,
CONCAT(B.TLLANG, B.TLISBN) ,
TRIM(GATLTH) ,
TRIM(B.TLUXCD) ,
TRIM(B.TLAUTH) ,
TRIM(B.TLTITL) ,
TRIM(B.TLFTP1 || B.TLFTP2 || B.TLFTP3) ,
TRIM(A5RPDF) ,	
TRIM(B.TLPROD) ,
TRIM(COALESCE(B3VDED, '')),
TRIM(BXPROD),
TRIM(B.TLSTAT) , 
TRIM(B.TLXDCD) ,
TRIM(B.TLFFCD) ,
TRIM(B.TLW0CD) ,
TRIM(BXP6DD),
TRIM(A5SJDF) ,
TRIM(A6T0DF) ,
TRIM(A6AXEE) ,
TRIM(A6AYEE) ,
TRIM(EBSJDF) ,
TRIM(EBT0DF) ,
TRIM(BWFMEE) , 
TRIM(BWFNEE) ,
TRIM(B.TLEDIT) ,
TRIM(A5X5ED) ,
distadmin.CVTDATE(B.TLULDT),
B.TLE6PR ,
us.TLE6PR,
uk.TLE6PR,
TRIM(BLW8CR) ,
TRIM(A5X4ED) )
--WHERE GBPM_LIST_PRICE!= US_LIST_PRICE;
